sudo: required
dist: trusty
services:
  - docker

before_install:
  - docker pull blang/latex
  - docker run --rm -i --user="$(id -u):$(id -g)" -v $PWD:/data blang/latex /bin/sh -c "make build"
  - docker ps -a
  - openssl aes-256-cbc -K $encrypted_4c3ccf0f1786_key -iv $encrypted_4c3ccf0f1786_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d
  - chmod a+x dropbox_uploader.sh

script:
- docker run --rm -i --user="$(id -u):$(id -g)" -v $PWD:/data blang/latex /bin/sh -c "make build"
- make log
- make upload
after_failure:
- "[ -f ~/.dropbox_uploader ] && ./dropbox_uploader.sh upload t/results/ travis-artifacts/$TRAVIS_JOB_NUMBER/"
