sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
script:
- xelatex cv-fr.tex
- xelatex cv-fr.tex
- xelatex cv-en.tex
- xelatex cv-en.tex
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - cv-fr.pdf
  - cv-en.pdf
  skip_cleanup: true
  on:
    tags: true
