before_install:
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_4c3ccf0f1786_key -iv $encrypted_4c3ccf0f1786_iv -in dropbox_uploader.sh.enc -out ./dropbox_uploader.sh -d'

install:
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended 
    - sudo apt-get install chktex

script:
    - make build
    - make test
    - make upload
  
deploy:
  provider: releases
  api_key:
      secure: [YOUR KEY]
  file:
      - cv-fr.pdf
      - cv-en.pdf
  skip_cleanup: true
  on:
      tags: true

after_failure:
  - '[ -f ~/.dropbox_uploader ] && ./dropbox_uploader.sh upload t/results/ travis-artifacts/$TRAVIS_JOB_NUMBER/'
